#! /bin/bash
srcDir="/home/lifeix/workspace/lifeix-pintimes-android"
destDir=/home/lifeix/temp/d3/move
demoDir=/home/lifeix/workspace_android/zhch_android_demo
srcPre="src/com/lifeix/pintimes"

# 建立目录, 清空内容
if [ -e "$destDir" ] ;then 
    rm -r $destDir/*
else
    mkdir  $destDir
fi

# coopy 源文件
srcs=("widget/drawerbox/DrawerBox.java"
"widget/drawerbox/TouchDisableView.java"
"app/Pintimes.java"
"user/UserService.java"
"user/vo/User.java"
"util"
"constant"
)
src_delete=("util/FakeData.java"
)
for file in ${srcs[@]};do
    destFile=$destDir/$srcPre/$file
    temp=`dirname "$destFile"`
    if [ ! -e $temp ] ; then
        mkdir -p $temp
    fi
    cp -r $srcDir/$srcPre/$file $destFile
done

for file in ${src_delete[@]};do
    destFile=$destDir/$srcPre/$file
    rm $destFile
done

# copy res
res=("anim/widget_drawer_close.xml"
"anim/widget_drawer_open.xml"
"drawable/selector_btn_main.xml"
"drawable/border_in_deep.xml"
"drawable/border_in_deep_round3.xml"
"drawable/border_circle_gray.xml"
"drawable/bg_btn_main_round3.xml"
"drawable/bg_btn_main_round3_selected.xml"
)
mkdir  -p $destDir/res/anim  $destDir/res/drawable  $destDir/res/layout  $destDir/res/values 
for file in ${res[@]}; do
    cp $srcDir/res/$file  $destDir/res/$file
done


sed -i "s/com.lifeix.pintimes/com.zhch.andex/g" `grep "com.lifeix.pintimes" -rl $destDir`
mv $destDir/src/com/lifeix/pintimes  $destDir/src/com/lifeix/andex
mv $destDir/src/com/lifeix  $destDir/src/com/zhch

cp -r $destDir/*  $demoDir/
