#! /bin/bash
srcDir="/home/lifeix/workspace/lifeix-pintimes-android"
destDir=/home/lifeix/temp/d3/move
demoDir=/home/lifeix/workspace_android/zhch_android_demo
srcPre="src/com/lifeix/pintimes"

# 建立目录, 清空内容
if [ -e "$destDir" ] ;then 
    rm -r $destDir/*
else
    mkdir  $destDir
fi

# coopy 源文件
srcs=("widget/drawerbox/DrawerBox.java"
"widget/drawerbox/TouchDisableView.java"
)
for file in ${srcs[@]};do
    destFile=$destDir/$srcPre/$file
    temp=`dirname "$destFile"`
    if [ ! -e $temp ] ; then
        mkdir -p $temp
    fi
    cp $srcDir/$srcPre/$file $destFile
done

# copy res
res=()


sed -i "s/com.lifeix.pintimes/com.zhch.andex/g" `grep "com.lifeix.pintimes" -rl $destDir`
mv $destDir/src/com/lifeix/pintimes  $destDir/src/com/lifeix/andex
mv $destDir/src/com/lifeix  $destDir/src/com/zhch

cp -r $destDir/*  $demoDir/
